const fs = require('fs');
const filePath = 'src/main.jsx';
const cssPath = 'src/style.css';
let content = fs.readFileSync(filePath, 'utf8');
let changed = 0;

const es = `  es: {
    app: "ÖZER BEND PRO V126",
    dims: "DIMENSIONES",
    profile: "PERFIL",
    settings: "AJUSTES",
    results: "RESULTADOS DE CORTE",
    cw: "Ancho de corte",
    ch: "Longitud de corte",
    draw: "2D",
    pdf: "PDF",
    print: "IMPRIMIR",
    share: "COMPARTIR",
    loading: "INICIANDO...",
    view3d: "3D",
    machineLabel: "Máquina",
    lowerDieLabel: "Matriz Inferior",
    upperDieLabel: "Punzón Superior",
    materialLabel: "Material",
    thicknessLabel: "Espesor de Chapa",
    insideRLabel: "Radio Interior",
    angleLabel: "Ángulo de Plegado",
    deductLabel: "Deducción de 15 mm",
    bdAutoLabel: "BD Automático",
    bdUnit: "mm / pliegue",
    manualBdToggle: "BD Manual",
    manualBdInputLabel: "BD Manual mm / pliegue",
    hardoxWarning: "⚠️ El valor automático de BD para Hardox es una estimación NO VERIFICADA. No inicie la producción sin un pliegue de prueba real — introduzca el valor medido en un pliegue de prueba usando «BD Manual».",
    feedbackBtn: "📩 Enviar Comentarios",
    feedbackSubjectManual: "ÖZER BEND PRO - Comentarios",
    feedbackGreeting: "Hola,\\n\\nMi comentario/problema sobre la app:\\n\\n",
    autoErrorSubject: "ÖZER BEND PRO - Informe de Error Automático",
    autoErrorPrefix: "Ocurrió un error inesperado en la app:\\n",
    autoErrorSuffix: "\\n\\n¿Desea informar este error al desarrollador por correo electrónico?",
    unknownError: "Error desconocido",
    unknownPromiseError: "Error de promise desconocido",
    lockedBadge: "V114 BLOQUEADO",
    cornerSingleBend: "ESQUINA (L) • PLIEGUE ÚNICO",
    lengthWord: "LONGITUD",
    leftWord: "Izquierda",
    rightWord: "Derecha",
    bottomLeftWord: "Inferior Izquierda",
    bottomRightWord: "Inferior Derecha",
    genelProfil: "PERFIL GENERAL",
    segmentUzunluk: "Longitud",
    segmentAci: "Ángulo",
    segmentYon: "Dirección",
    yonYukari: "Arriba",
    yonAsagi: "Abajo",
    segmentEkle: "+ Añadir Segmento",
    segmentSil: "Quitar",
    favorites: "Favoritos",
    favSave: "Guardar",
    favLoad: "Cargar",
    favDelete: "Eliminar",
    favEmpty: "No hay favoritos guardados.",
    favNamePrompt: "Nombre del favorito:",
    toplamUzunluk: "Longitud Total de Corte",
    bukumSayisi: "Número de Pliegues",
    segment: "Segmento"
  }`;

const it = `  it: {
    app: "ÖZER BEND PRO V126",
    dims: "DIMENSIONI",
    profile: "PROFILO",
    settings: "IMPOSTAZIONI",
    results: "RISULTATI DI TAGLIO",
    cw: "Larghezza di taglio",
    ch: "Lunghezza di taglio",
    draw: "2D",
    pdf: "PDF",
    print: "STAMPA",
    share: "CONDIVIDI",
    loading: "AVVIO...",
    view3d: "3D",
    machineLabel: "Macchina",
    lowerDieLabel: "Matrice Inferiore",
    upperDieLabel: "Punzone Superiore",
    materialLabel: "Materiale",
    thicknessLabel: "Spessore Lamiera",
    insideRLabel: "Raggio Interno",
    angleLabel: "Angolo di Piega",
    deductLabel: "Detrazione 15 mm",
    bdAutoLabel: "BD Automatico",
    bdUnit: "mm / piega",
    manualBdToggle: "BD Manuale",
    manualBdInputLabel: "BD Manuale mm / piega",
    hardoxWarning: "⚠️ Il valore automatico di BD per Hardox è una stima NON VERIFICATA. Non avviare la produzione senza una piega di prova reale — inserisci il valore misurato da una piega di prova usando «BD Manuale».",
    feedbackBtn: "📩 Invia Feedback",
    feedbackSubjectManual: "ÖZER BEND PRO - Feedback",
    feedbackGreeting: "Ciao,\\n\\nIl mio feedback/problema sull'app:\\n\\n",
    autoErrorSubject: "ÖZER BEND PRO - Segnalazione Errore Automatica",
    autoErrorPrefix: "Si è verificato un errore imprevisto nell'app:\\n",
    autoErrorSuffix: "\\n\\nVuoi segnalare questo errore allo sviluppatore via email?",
    unknownError: "Errore sconosciuto",
    unknownPromiseError: "Errore di promise sconosciuto",
    lockedBadge: "V114 BLOCCATO",
    cornerSingleBend: "ANGOLO (L) • PIEGA SINGOLA",
    lengthWord: "LUNGHEZZA",
    leftWord: "Sinistra",
    rightWord: "Destra",
    bottomLeftWord: "In Basso a Sinistra",
    bottomRightWord: "In Basso a Destra",
    genelProfil: "PROFILO GENERALE",
    segmentUzunluk: "Lunghezza",
    segmentAci: "Angolo",
    segmentYon: "Direzione",
    yonYukari: "Su",
    yonAsagi: "Giù",
    segmentEkle: "+ Aggiungi Segmento",
    segmentSil: "Rimuovi",
    favorites: "Preferiti",
    favSave: "Salva",
    favLoad: "Carica",
    favDelete: "Elimina",
    favEmpty: "Nessun preferito salvato.",
    favNamePrompt: "Nome preferito:",
    toplamUzunluk: "Lunghezza Totale di Taglio",
    bukumSayisi: "Numero di Pieghe",
    segment: "Segmento"
  }`;

const ru = `  ru: {
    app: "ÖZER BEND PRO V126",
    dims: "РАЗМЕРЫ",
    profile: "ПРОФИЛЬ",
    settings: "НАСТРОЙКИ",
    results: "РЕЗУЛЬТАТЫ РАСКРОЯ",
    cw: "Ширина раскроя",
    ch: "Длина раскроя",
    draw: "2D",
    pdf: "PDF",
    print: "ПЕЧАТЬ",
    share: "ПОДЕЛИТЬСЯ",
    loading: "ЗАПУСК...",
    view3d: "3D",
    machineLabel: "Станок",
    lowerDieLabel: "Нижний штамп",
    upperDieLabel: "Верхний пуансон",
    materialLabel: "Материал",
    thicknessLabel: "Толщина листа",
    insideRLabel: "Внутренний радиус",
    angleLabel: "Угол гиба",
    deductLabel: "Вычет 15 мм",
    bdAutoLabel: "Авто BD",
    bdUnit: "мм / гиб",
    manualBdToggle: "Ручной BD",
    manualBdInputLabel: "Ручной BD мм / гиб",
    hardoxWarning: "⚠️ Автоматическое значение BD для Hardox является неподтверждённой оценкой. Не начинайте производство без реального пробного гиба — введите значение, измеренное на пробном гибе, используя «Ручной BD».",
    feedbackBtn: "📩 Отправить отзыв",
    feedbackSubjectManual: "ÖZER BEND PRO - Отзыв",
    feedbackGreeting: "Здравствуйте,\\n\\nМой отзыв/проблема о приложении:\\n\\n",
    autoErrorSubject: "ÖZER BEND PRO - Автоматический отчёт об ошибке",
    autoErrorPrefix: "В приложении произошла непредвиденная ошибка:\\n",
    autoErrorSuffix: "\\n\\nХотите сообщить об этой ошибке разработчику по электронной почте?",
    unknownError: "Неизвестная ошибка",
    unknownPromiseError: "Неизвестная ошибка promise",
    lockedBadge: "V114 ЗАБЛОКИРОВАНО",
    cornerSingleBend: "УГОЛ (L) • ОДИНОЧНЫЙ ГИБ",
    lengthWord: "ДЛИНА",
    leftWord: "Левый",
    rightWord: "Правый",
    bottomLeftWord: "Нижний левый",
    bottomRightWord: "Нижний правый",
    genelProfil: "ОБЩИЙ ПРОФИЛЬ",
    segmentUzunluk: "Длина",
    segmentAci: "Угол",
    segmentYon: "Направление",
    yonYukari: "Вверх",
    yonAsagi: "Вниз",
    segmentEkle: "+ Добавить сегмент",
    segmentSil: "Удалить",
    favorites: "Избранное",
    favSave: "Сохранить",
    favLoad: "Загрузить",
    favDelete: "Удалить",
    favEmpty: "Нет сохранённых избранных.",
    favNamePrompt: "Название избранного:",
    toplamUzunluk: "Общая длина раскроя",
    bukumSayisi: "Количество гибов",
    segment: "Сегмент"
  }`;

const pt = `  pt: {
    app: "ÖZER BEND PRO V126",
    dims: "DIMENSÕES",
    profile: "PERFIL",
    settings: "CONFIGURAÇÕES",
    results: "RESULTADOS DE CORTE",
    cw: "Largura de corte",
    ch: "Comprimento de corte",
    draw: "2D",
    pdf: "PDF",
    print: "IMPRIMIR",
    share: "COMPARTILHAR",
    loading: "INICIANDO...",
    view3d: "3D",
    machineLabel: "Máquina",
    lowerDieLabel: "Matriz Inferior",
    upperDieLabel: "Punção Superior",
    materialLabel: "Material",
    thicknessLabel: "Espessura da Chapa",
    insideRLabel: "Raio Interno",
    angleLabel: "Ângulo de Dobra",
    deductLabel: "Dedução de 15 mm",
    bdAutoLabel: "BD Automático",
    bdUnit: "mm / dobra",
    manualBdToggle: "BD Manual",
    manualBdInputLabel: "BD Manual mm / dobra",
    hardoxWarning: "⚠️ O valor automático de BD para Hardox é uma estimativa NÃO VERIFICADA. Não inicie a produção sem uma dobra de teste real — insira o valor medido em uma dobra de teste usando «BD Manual».",
    feedbackBtn: "📩 Enviar Feedback",
    feedbackSubjectManual: "ÖZER BEND PRO - Feedback",
    feedbackGreeting: "Olá,\\n\\nMeu feedback/problema sobre o app:\\n\\n",
    autoErrorSubject: "ÖZER BEND PRO - Relatório de Erro Automático",
    autoErrorPrefix: "Ocorreu um erro inesperado no app:\\n",
    autoErrorSuffix: "\\n\\nDeseja relatar este erro ao desenvolvedor por e-mail?",
    unknownError: "Erro desconhecido",
    unknownPromiseError: "Erro de promise desconhecido",
    lockedBadge: "V114 BLOQUEADO",
    cornerSingleBend: "CANTO (L) • DOBRA ÚNICA",
    lengthWord: "COMPRIMENTO",
    leftWord: "Esquerda",
    rightWord: "Direita",
    bottomLeftWord: "Inferior Esquerda",
    bottomRightWord: "Inferior Direita",
    genelProfil: "PERFIL GERAL",
    segmentUzunluk: "Comprimento",
    segmentAci: "Ângulo",
    segmentYon: "Direção",
    yonYukari: "Cima",
    yonAsagi: "Baixo",
    segmentEkle: "+ Adicionar Segmento",
    segmentSil: "Remover",
    favorites: "Favoritos",
    favSave: "Salvar",
    favLoad: "Carregar",
    favDelete: "Excluir",
    favEmpty: "Nenhum favorito salvo.",
    favNamePrompt: "Nome do favorito:",
    toplamUzunluk: "Comprimento Total de Corte",
    bukumSayisi: "Número de Dobras",
    segment: "Segmento"
  }`;

const pl = `  pl: {
    app: "ÖZER BEND PRO V126",
    dims: "WYMIARY",
    profile: "PROFIL",
    settings: "USTAWIENIA",
    results: "WYNIKI CIĘCIA",
    cw: "Szerokość cięcia",
    ch: "Długość cięcia",
    draw: "2D",
    pdf: "PDF",
    print: "DRUKUJ",
    share: "UDOSTĘPNIJ",
    loading: "URUCHAMIANIE...",
    view3d: "3D",
    machineLabel: "Maszyna",
    lowerDieLabel: "Matryca Dolna",
    upperDieLabel: "Stempel Górny",
    materialLabel: "Materiał",
    thicknessLabel: "Grubość Blachy",
    insideRLabel: "Promień Wewnętrzny",
    angleLabel: "Kąt Gięcia",
    deductLabel: "Odjęcie 15 mm",
    bdAutoLabel: "Auto BD",
    bdUnit: "mm / gięcie",
    manualBdToggle: "Ręczne BD",
    manualBdInputLabel: "Ręczne BD mm / gięcie",
    hardoxWarning: "⚠️ Automatyczna wartość BD dla Hardox jest niezweryfikowanym oszacowaniem. Nie rozpoczynaj produkcji bez rzeczywistego gięcia próbnego — wprowadź wartość zmierzoną z gięcia próbnego, używając «Ręczne BD».",
    feedbackBtn: "📩 Wyślij Opinię",
    feedbackSubjectManual: "ÖZER BEND PRO - Opinia",
    feedbackGreeting: "Cześć,\\n\\nMoja opinia/problem dotyczący aplikacji:\\n\\n",
    autoErrorSubject: "ÖZER BEND PRO - Automatyczny Raport Błędu",
    autoErrorPrefix: "W aplikacji wystąpił nieoczekiwany błąd:\\n",
    autoErrorSuffix: "\\n\\nCzy chcesz zgłosić ten błąd programiście e-mailem?",
    unknownError: "Nieznany błąd",
    unknownPromiseError: "Nieznany błąd promise",
    lockedBadge: "V114 ZABLOKOWANE",
    cornerSingleBend: "NAROŻNIK (L) • POJEDYNCZE GIĘCIE",
    lengthWord: "DŁUGOŚĆ",
    leftWord: "Lewy",
    rightWord: "Prawy",
    bottomLeftWord: "Dolny Lewy",
    bottomRightWord: "Dolny Prawy",
    genelProfil: "PROFIL OGÓLNY",
    segmentUzunluk: "Długość",
    segmentAci: "Kąt",
    segmentYon: "Kierunek",
    yonYukari: "Góra",
    yonAsagi: "Dół",
    segmentEkle: "+ Dodaj Segment",
    segmentSil: "Usuń",
    favorites: "Ulubione",
    favSave: "Zapisz",
    favLoad: "Wczytaj",
    favDelete: "Usuń",
    favEmpty: "Brak zapisanych ulubionych.",
    favNamePrompt: "Nazwa ulubionego:",
    toplamUzunluk: "Całkowita Długość Cięcia",
    bukumSayisi: "Liczba Gięć",
    segment: "Segment"
  }`;

const zh = `  zh: {
    app: "ÖZER BEND PRO V126",
    dims: "尺寸",
    profile: "型材",
    settings: "设置",
    results: "切割结果",
    cw: "切割宽度",
    ch: "切割长度",
    draw: "2D",
    pdf: "PDF",
    print: "打印",
    share: "分享",
    loading: "启动中...",
    view3d: "3D",
    machineLabel: "机床",
    lowerDieLabel: "下模",
    upperDieLabel: "上模",
    materialLabel: "材料",
    thicknessLabel: "板材厚度",
    insideRLabel: "内半径",
    angleLabel: "弯曲角度",
    deductLabel: "15毫米扣除",
    bdAutoLabel: "自动BD",
    bdUnit: "毫米/弯",
    manualBdToggle: "手动BD",
    manualBdInputLabel: "手动BD 毫米/弯",
    hardoxWarning: "⚠️ Hardox材料的自动BD值为未经验证的估算值。请勿在没有实际试弯的情况下开始生产——请使用「手动BD」输入试弯测量的数值。",
    feedbackBtn: "📩 发送反馈",
    feedbackSubjectManual: "ÖZER BEND PRO - 反馈",
    feedbackGreeting: "您好，\\n\\n我对该应用的反馈/问题：\\n\\n",
    autoErrorSubject: "ÖZER BEND PRO - 自动错误报告",
    autoErrorPrefix: "应用程序发生意外错误：\\n",
    autoErrorSuffix: "\\n\\n是否要通过电子邮件向开发者报告此错误？",
    unknownError: "未知错误",
    unknownPromiseError: "未知的Promise错误",
    lockedBadge: "V114 已锁定",
    cornerSingleBend: "转角(L) • 单弯",
    lengthWord: "长度",
    leftWord: "左",
    rightWord: "右",
    bottomLeftWord: "左下",
    bottomRightWord: "右下",
    genelProfil: "通用型材",
    segmentUzunluk: "长度",
    segmentAci: "角度",
    segmentYon: "方向",
    yonYukari: "向上",
    yonAsagi: "向下",
    segmentEkle: "+ 添加段",
    segmentSil: "删除",
    favorites: "收藏",
    favSave: "保存",
    favLoad: "加载",
    favDelete: "删除",
    favEmpty: "没有已保存的收藏。",
    favNamePrompt: "收藏名称：",
    toplamUzunluk: "总切割长度",
    bukumSayisi: "弯曲次数",
    segment: "段"
  }`;

const ar = `  ar: {
    app: "ÖZER BEND PRO V126",
    dims: "الأبعاد",
    profile: "الملف",
    settings: "الإعدادات",
    results: "نتائج القص",
    cw: "عرض القص",
    ch: "طول القص",
    draw: "2D",
    pdf: "PDF",
    print: "طباعة",
    share: "مشاركة",
    loading: "جارٍ البدء...",
    view3d: "3D",
    machineLabel: "الماكينة",
    lowerDieLabel: "القالب السفلي",
    upperDieLabel: "المكبس العلوي",
    materialLabel: "المادة",
    thicknessLabel: "سماكة الصفيحة",
    insideRLabel: "نصف القطر الداخلي",
    angleLabel: "زاوية الثني",
    deductLabel: "خصم 15 مم",
    bdAutoLabel: "BD تلقائي",
    bdUnit: "مم / ثنية",
    manualBdToggle: "BD يدوي",
    manualBdInputLabel: "BD يدوي مم / ثنية",
    hardoxWarning: "⚠️ قيمة BD التلقائية لمادة Hardox هي تقدير غير مؤكد. لا تبدأ الإنتاج دون ثنية اختبار حقيقية — أدخل القيمة المقاسة من ثنية اختبار باستخدام «BD يدوي».",
    feedbackBtn: "📩 إرسال ملاحظات",
    feedbackSubjectManual: "ÖZER BEND PRO - ملاحظات",
    feedbackGreeting: "مرحباً،\\n\\nملاحظاتي/مشكلتي حول التطبيق:\\n\\n",
    autoErrorSubject: "ÖZER BEND PRO - تقرير خطأ تلقائي",
    autoErrorPrefix: "حدث خطأ غير متوقع في التطبيق:\\n",
    autoErrorSuffix: "\\n\\nهل تريد الإبلاغ عن هذا الخطأ للمطور عبر البريد الإلكتروني؟",
    unknownError: "خطأ غير معروف",
    unknownPromiseError: "خطأ promise غير معروف",
    lockedBadge: "V114 مقفل",
    cornerSingleBend: "زاوية (L) • ثنية واحدة",
    lengthWord: "الطول",
    leftWord: "يسار",
    rightWord: "يمين",
    bottomLeftWord: "أسفل يسار",
    bottomRightWord: "أسفل يمين",
    genelProfil: "ملف عام",
    segmentUzunluk: "الطول",
    segmentAci: "الزاوية",
    segmentYon: "الاتجاه",
    yonYukari: "أعلى",
    yonAsagi: "أسفل",
    segmentEkle: "+ إضافة قطعة",
    segmentSil: "إزالة",
    favorites: "المفضلة",
    favSave: "حفظ",
    favLoad: "تحميل",
    favDelete: "حذف",
    favEmpty: "لا توجد مفضلات محفوظة.",
    favNamePrompt: "اسم المفضلة:",
    toplamUzunluk: "إجمالي طول القص",
    bukumSayisi: "عدد الثنيات",
    segment: "قطعة"
  }`;

const dictEndRegex = /(\n  \})\n\};\n\nconst LANGUAGES = \[/;
if (dictEndRegex.test(content)) {
  content = content.replace(dictEndRegex, `$1,\n${es},\n${it},\n${ru},\n${pt},\n${pl},\n${zh},\n${ar}\n};\n\nconst LANGUAGES = [`);
  changed++;
} else {
  console.error('UYARI: DICT sonu bulunamadi (dictEndRegex).');
}

const langArrTarget = `{ code: "de", flag: "DE", label: "Deutsch" }\n];`;
const langArrReplacement = `{ code: "de", flag: "DE", label: "Deutsch" },
  { code: "es", flag: "ES", label: "Español" },
  { code: "it", flag: "IT", label: "Italiano" },
  { code: "ru", flag: "RU", label: "Русский" },
  { code: "pt", flag: "PT", label: "Português" },
  { code: "pl", flag: "PL", label: "Polski" },
  { code: "zh", flag: "CN", label: "中文" },
  { code: "ar", flag: "SA", label: "العربية" }
];`;

if (content.includes(langArrTarget)) {
  content = content.replace(langArrTarget, langArrReplacement);
  changed++;
} else {
  console.error('UYARI: LANGUAGES dizisi hedefi bulunamadi.');
}

const mainTagTarget = `<main className="app">`;
const mainTagReplacement = `<main className="app" dir={lang === "ar" ? "rtl" : "ltr"}>`;
if (content.includes(mainTagTarget)) {
  content = content.replace(mainTagTarget, mainTagReplacement);
  changed++;
} else {
  console.error('UYARI: main.app etiketi bulunamadi (RTL dir eklenemedi).');
}

fs.writeFileSync(filePath, content, 'utf8');

const rtlCss = `

/* ==== RTL (Arapca) destegi ==== */
[dir="rtl"] {
  direction: rtl;
  text-align: right;
}

[dir="rtl"] .grid,
[dir="rtl"] .actions,
[dir="rtl"] .actionsSingle,
[dir="rtl"] .segmentRow,
[dir="rtl"] .segmentButtons,
[dir="rtl"] .favRow,
[dir="rtl"] .favWrap,
[dir="rtl"] .topButtons,
[dir="rtl"] .brand,
[dir="rtl"] .profileChoice,
[dir="rtl"] .langMenuWrap,
[dir="rtl"] .dimsHeaderRow {
  direction: rtl;
}

[dir="rtl"] input,
[dir="rtl"] select,
[dir="rtl"] label {
  text-align: right;
}

[dir="rtl"] .langMenu {
  right: auto;
  left: 0;
  text-align: right;
}

[dir="rtl"] .resultItem,
[dir="rtl"] .infoStrip div {
  flex-direction: row-reverse;
}
`;

fs.appendFileSync(cssPath, rtlCss);
console.log(`Tamamlandi. ${changed}/3 blok degistirildi (main.jsx). RTL CSS eklendi.`);
